feat: truncate or wrap options lables on long text
unepwcmc/wcmc-components pull request #23
Opened 2021-10-05 15:14 UTC by RainbowGiantSquid

2021-10-05 15:16 UTC, defaye commented on src/components/filterable-table/TableFilterOption.vue
> +      for (const key in this.config.filters.filterOptions.labels) {
I'd probably try to build this from an array and at the end simply returning an array is sufficient. Classes can be applied as a string, an array of classes or even as an object as keys, with truthy values determining whether they are applied or not

2021-10-05 15:18 UTC, defaye commented on src/components/filterable-table/TableFilterOption.vue
> +      for (const key in this.config.filters.filterOptions.labels) {
You can probably just return `this.config.filters.filterOptions.labels` or if you explicitly need to see `true` then you can use some `.filter` method perhaps to get a subset returned as an array

2021-10-05 15:51 UTC, RainbowGiantSquid commented on src/components/filterable-table/TableFilterOption.vue
> +      for (const key in this.config.filters.filterOptions.labels) {
I have changed labels to array and passed as a string

2021-10-05 16:55 UTC, defaye requested changes

2021-10-05 16:55 UTC, defaye commented on src/components/filterable-table/TableFilterOption.vue
> +    labelClasses () {
Do we have an example of what the filterOptions look like? It might be worth adding this in some comments above, because it's currently a little mysterious and means that without running the code and debugging, there's no way to know if the implementation is sufficient

2021-10-05 16:55 UTC, defaye commented on src/components/filterable-table/TableFilterOption.vue
> +    <label :for="optionId" :class="`label ${labelClasses}`">{{ option }}</label>
You can refactor this to be 
```
:class="['label', labelClasses]"
```

You could even write it as  `class="label" :class="labelClasses"` 

This means that you then only need to supply an array of the labelClasses, rather than being forced to convert them into a string. 

See https://vuejs.org/v2/guide/class-and-style.html#Object-Syntax and https://vuejs.org/v2/guide/class-and-style.html#Array-Syntax

2021-10-05 17:12 UTC, RainbowGiantSquid commented on src/components/filterable-table/TableFilterOption.vue
> +    <label :for="optionId" :class="`label ${labelClasses}`">{{ option }}</label>
Wow, that's amazing thank you!

2021-10-05 17:51 UTC, RainbowGiantSquid commented on src/components/filterable-table/TableFilterOption.vue
> +    labelClasses () {
comment added and property renamed for clarity

2021-10-06 09:08 UTC, RainbowGiantSquid commented on src/components/filterable-table/constants.js
> +      handleLongLabels:'truncate',
ah good point - I'll remove comments from here

2021-10-06 09:08 UTC, RainbowGiantSquid commented on src/components/filterable-table/TableFilterOption.vue
> +    labelClasses () {
Thank you! I'll update the comment and regenerate the doc file for this.

2021-10-06 09:53 UTC, defaye approved these changes

2021-10-07 09:48 UTC, merged