Feat/sorting
unepwcmc/wcmc-components pull request #38
Opened 2022-03-28 11:26 UTC by Joseph-Burke

2022-03-28 12:19 UTC, Joseph-Burke commented on dev/Serve.vue
> +    </filterable-table>
Just an example I thought might be nice to include to show how a custom sorting icon can be added.

2022-03-28 12:19 UTC, Joseph-Burke commented on src/components/filterable-table/FilterableTable.vue
> +    </portal>
Using Vue Portal means we don't have to pass slots down the component tree.

2022-03-28 12:19 UTC, Joseph-Burke commented on src/components/filterable-table/FilterableTable.vue
> +          {{ noResultsMessage }}
A small optimisation

2022-03-28 12:19 UTC, Joseph-Burke commented on src/components/filterable-table/TableHeading.vue
> +          <svg-sort-icon class="sort-icon"/> <!-- Default sort icon -->
The default sort icon, with an explanatory comment

2022-03-28 12:19 UTC, Joseph-Burke commented on src/components/filterable-table/TableHeading.vue
> +      return this.currentSort(this.tableId).column == this.heading.field
I had to write these as methods, because when I first tried to do it with computed properties it wasn't working...? But if there's a better way to do this then I'd be happy to do so

2022-03-29 13:53 UTC, yndajas requested changes
Still need to look through the `src/components/filterable-table/FilterableTable.vue` component, but I've reviewed the other files. Submitting this review now as I need to head off, but thought you might want to take a look this afternoon!

2022-03-29 13:53 UTC, yndajas commented on src/components/filterable-table/TableHeading.vue
> +      return this.currentSort(this.tableId).column == this.heading.field
I think the reason is `this.currentSort` is a function that returns something from the store, and a computed method doesn't automatically know when the return value of a function changes? You could probably get around if when you update the store in `applySort`, you then also update something in the component's state with the new value, then base the `isNewSortAscending` and `isColumnCurrentlySorted` methods off that - I think they should then work in computed. Basically move the stuff that they're relying on into things that they can watch for changes

Other than possibly doing the above (I'm not sure have a duplicate of the store state in the component state is a cleaner option to be honest), can you use `===` here?

2022-03-29 13:53 UTC, yndajas commented on src/components/filterable-table/TableHeading.vue
> +        {{ heading.title }}
Not really related to your code here, but this can use `v-text`

2022-03-29 13:53 UTC, yndajas commented on src/components/filterable-table/TableHeading.vue
> +      <div class="sorting-toggle" @click="applySort()">
I think this needs to be conditional upon some option, so that we can hide the sorting toggles if the project doesn't need/want sorting

Related to this, did we establish how we're managing backwards compatibility - are we versioning this in some way? Is that more of an npm deployment issue?

2022-03-29 13:53 UTC, yndajas commented on src/components/filterable-table/TableHeading.vue
> +    buildSortingPayload () {
If you do get the `is` methods working as computed, I think this one can be too, but you might need to use some `const`s for the object's values before returning it

2022-03-29 13:53 UTC, yndajas commented on src/components/filterable-table/TableHeading.vue
> +    applySort () {
Is there a reason for the method rename here? `sort` seems like a more direct way of expressing the same thing to me

2022-03-29 13:53 UTC, yndajas commented on src/components/filterable-table/TableHeading.vue
> +      }
I think you could express this more concisely like:
```
const currentlySorted = this.isColumnCurrentlySorted()
return !currentlySorted || !this.currentSort(this.tableId).ascending
```

Though it might be nice to use a variable for the right of the `||`, e.g. `notCurrentlyAscending`

2022-03-29 13:53 UTC, yndajas commented on src/components/filterable-table/svgs/SvgSortIcon.vue
> +  <svg xmlns="http://www.w3.org/2000/svg" width="10.305" height="12.305" viewBox="0 0 10.305 12.305">
Generally best just to use `viewBox` then set the height and width in the component that calls this. You can run it through [SVGOMG](https://jakearchibald.github.io/svgomg/) with "Prefer viewBox to width/height" set to get nice markup

2022-03-29 13:53 UTC, yndajas commented on src/components/filterable-table/store.js
> +  selectedSort: { column: null, ascending: true }, // column:string (to equal the name of one of the table's columns), ascending:boolean
Can this be broken onto multiple lines?

2022-03-29 14:57 UTC, Joseph-Burke commented on dev/Serve.vue
> + <!-- <template #sort-icon>
I've edited it so that the comment tags have their own lines, which I think looks neater, is that what you mean?

<img width="720" alt="image" src="https://user-images.githubusercontent.com/56026099/160641048-84130b20-eb45-4f27-9f65-cf897ca1a38a.png">

2022-03-30 09:48 UTC, Joseph-Burke commented on src/components/filterable-table/TableHeading.vue
> +      }
Really nice expression of that logic, will refactor it now :)

2022-03-30 09:58 UTC, Joseph-Burke commented on src/components/filterable-table/TableHeading.vue
> +      }
Refactored a little and ended up with this. What do you think? I do find the return statement here very human-comprehensible

<img width="739" alt="image" src="https://user-images.githubusercontent.com/56026099/160805023-bbf474f0-56bd-4a16-8083-6d24a15036d6.png">

2022-03-30 11:07 UTC, Joseph-Burke commented on src/components/filterable-table/svgs/SvgSortIcon.vue
> +  <svg xmlns="http://www.w3.org/2000/svg" width="10.305" height="12.305" viewBox="0 0 10.305 12.305">
Nice. I ran it through SVGOMG with the "Prefer viewBox to width/height" setting and put that generated markup into the component.

I've also replaced the hard-coded colour in the SVG with "currentColor", and set that in TableHeading when the Svg is rendered.

2022-03-30 11:09 UTC, Joseph-Burke commented on src/components/filterable-table/TableHeading.vue
> +    applySort () {
I've switched this to `sortColumn` for now

2022-03-30 11:38 UTC, yndajas commented on src/components/filterable-table/TableHeading.vue
> +      }
Looks good, but I think you need a `!` on line 96?

2022-03-30 11:48 UTC, Joseph-Burke commented on src/components/filterable-table/TableHeading.vue
> +      <div class="sorting-toggle" @click="applySort()">
Yep, that's a very good point.

There's already an `options` prop on the FilterableTable, so I've just added a `sortable` key to that options object (and set it the default value to false). So then it kind of piggybacks on the existing process we have. That options object is imported into the store, and then the table heading component can read it to determine whether or not to display the sorting toggle.

As for the general issue of backwards compatibility, I want to changes here to be part of a 1.2.0 release (both here and on NPM). It is basically backwards compatible, especially since `options.sortable` defaults to `false`. The exception to that is that a "sort" parameter will now be sent in the Axios request, regardless of whether the table is sortable or not. This isn't _ideal_, but also the backend gem will only deal with parameters it expects so it should be a "no harm, no foul" kind of situation?

I could make a change so that that parameter will only be sent if the table's options has `sortable: true`...What do you think?

2022-03-31 07:41 UTC, Joseph-Burke commented on src/components/filterable-table/TableHeading.vue
> +      <div class="sorting-toggle" @click="applySort()">
I have implemented the above idea now. The parameter will only be sent if the `sortable: true` option is present, so these changes will only affect devs who opt in to the sortable table

2022-03-31 07:50 UTC, Joseph-Burke commented on src/components/filterable-table/TableHeading.vue
> +      }
Fixed :)

2022-03-31 07:56 UTC, Joseph-Burke commented on src/components/filterable-table/TableHeading.vue
> +      return this.currentSort(this.tableId).column == this.heading.field
I read into it [here](https://v2.vuejs.org/v2/guide/reactivity.html#For-Arrays) and got a fix. 

Basically our `tables` array is initialised with a length of 0, and Vue only knows to check reactivty for Object properties that are present at initialisation. Now, when a new table is added to that array, it is done using `Vue.set`, which updates the reactivity to include the new item.

That's what I understand from it anyway...in any case it's working now and I've moved all those methods over to be computed properties

2022-03-31 10:25 UTC, yndajas commented on dev/Serve.vue
> + <!-- <template #sort-icon>
That works! It looks like line 14 is one space extra indented versus line 11

2022-03-31 10:52 UTC, yndajas commented on src/components/filterable-table/FilterableTable.vue
> +        requested_page: this.requestedPage(this.id),
I really like all these store method refactors!

2022-03-31 10:52 UTC, yndajas commented on src/components/filterable-table/FilterableTable.vue
>        let data = {
Since this is an object, `const` should be fine, unless the whole object needs replacing at any point?

2022-03-31 10:52 UTC, yndajas commented on src/components/filterable-table/FilterableTable.vue
> +        data += { ...data, sort: this.selectedSort(this.id) }
Then here, instead of `data +=` you should be able to just say `data.sort = this.selectedSort(this.id)`

If you do need to replace the whole object for some reason, `=` should be fine (instead of `+=`) since you're using the spread operator to get the existing key/value pairs

2022-03-31 10:52 UTC, yndajas commented on src/components/filterable-table/TableHeading.vue
> +          <svg-sort-icon class="sort-icon" width="10.305" height="12.305" currentColor="#fff"/> <!-- Default sort icon -->
This should be `color` as a CSS declaration not `currentColor` as a HTML attribute - `currentColor` in the SVG will be based on the `color` CSS property

Probably best to also move the width and height to CSS declarations in the style section, and use `rem`s

2022-03-31 10:52 UTC, yndajas commented on src/components/filterable-table/TableHeading.vue
>    computed: {
Is there a logic to the ordering here? It seems a bit random from a glance - alphabetical and/or by feature might be best?

2022-03-31 10:52 UTC, yndajas commented on src/components/filterable-table/TableHeading.vue
> +      <div class="sorting-toggle" @click="applySort()">
Sounds good!

2022-03-31 10:53 UTC, yndajas commented on src/components/filterable-table/TableHeading.vue
> +    applySort () {
Also sounds good. I suppose I would opt for always using a leading verb in method names (not sure if I do this consistently in practice!), and as an extension assume `sort` is a verb, but this works!

2022-03-31 11:02 UTC, Joseph-Burke commented on src/components/filterable-table/TableHeading.vue
> +          <svg-sort-icon class="sort-icon" width="10.305" height="12.305" currentColor="#fff"/> <!-- Default sort icon -->
Aaah, sorry. Got you

2022-03-31 11:18 UTC, yndajas requested changes
Looks good! Just a few minor comments now, some of which are just additional tidy ups we could do of the old code, since the latest commits have formatted a bunch of non-sort-related components

2022-03-31 11:18 UTC, yndajas commented on src/components/filterable-table/TableLegend.vue
> +            @click="closeModal()"
Looks like you did this for the new sort method, but I think here we can also skip the brackets, so just `@click="closeModal"`. I realise the changes here are just code style, but might be a nice small update!

2022-03-31 11:18 UTC, yndajas commented on src/components/filterable-table/TableLegend.vue
> +        :class="`legend__icon ${config.legend.buttonClass}`"
I think it's usually preferable to write this like:

```
class="legend__icon"
:class="config.legend.buttonClass"
```

So you're separating out the static and dynamic classes. But as there's just one of each, I think it's fine to use `:class` for both

2022-03-31 11:18 UTC, yndajas commented on src/components/filterable-table/TableModal.vue
> +                  v-for="string, index in item.value"
Here and on line 40, the arguments in the `v-for`s aren't wrapped in parentheses, but elsewhere in the project where there are multiple arguments they are

2022-03-31 11:18 UTC, yndajas commented on src/components/filterable-table/TableRow.vue
> +      return url.includes('http') ? `<a href="${url}" title="View assessment" target="_blank">Link</a>` : url
Another one not really resulting from this PR, but as there are a bunch of style edits, maybe the HTML here can be abstracted into a `const` to clean up this `return` statement a little

2022-03-31 11:18 UTC, yndajas commented on src/components/filterable-table/store.js
> +import Vue from 'vue'
Can we just import `set` instead of all of Vue?

2022-03-31 11:18 UTC, yndajas commented on src/components/filterable-table/store.js
> +    isSortable: (_state, getters) => id => {
I'm guessing the underscored paramater is from a formatter - do we need this? It's not underscored elsewhere

2022-04-06 12:27 UTC, Joseph-Burke commented on dev/Serve.vue
> + <!-- <template #sort-icon>
Good spot! Just fixed it now

2022-04-06 12:53 UTC, Joseph-Burke commented on src/components/filterable-table/TableHeading.vue
>    computed: {
I was trying to do it in terms of like, derivative computed properties after the computed properties they depend on? So `table`, and then `options`, `currentSort`, since they use `table`. But it does come across as pretty random and I think alphabetical is probably best

2022-04-06 13:01 UTC, Joseph-Burke commented on src/components/filterable-table/TableLegend.vue
> +        :class="`legend__icon ${config.legend.buttonClass}`"
No, I agree with you here for sure. I've now separated `class` and `:class`

2022-04-06 13:55 UTC, Joseph-Burke commented on src/components/filterable-table/store.js
> +    isSortable: (_state, getters) => id => {
Ah yeah — this was recommended by VSCode hahaha. `state` is unused, but `getters` is, so the `_` prefix is to indicate that it's an unused variable

<img width="457" alt="image" src="https://user-images.githubusercontent.com/56026099/161990964-0aa3e9a8-baa1-4d8b-a7d9-5531b63288c2.png">

2022-04-06 13:55 UTC, merged