Feat/pagination development
unepwcmc/wcmc-components pull request #55
Opened 2022-07-04 19:33 UTC by Maxycle

2022-07-06 15:28 UTC, Joseph-Burke requested changes
@Maxycle 

The main issue here is that it seems that @unep-wcmc/wcmc-components 2.2.2 has already been published before this code has been reviewed, which is not ideal. I've also left a comment explaining why updates to the CHANGELOG.md and the release version should not be done in a feature branch, but rather in a release branch.

There are quite a number of things to fix up here, check out the comments ⬇️ 😃

2022-07-06 15:28 UTC, Joseph-Burke commented on src/components/filterable-table/TablePagination.vue
> +      return pages;
What's the purpose of the `pages` variable? 

It's assigned an empty array on 158, then it has integers pushed into it, then it's returned.

How about using lodash's [range function](https://lodash.com/docs/4.17.15#range)? You could remove `pages` entirely and just have:

```
return range(firstPageOnPagintation, lastPageOnPagination)
```

2022-07-06 15:28 UTC, Joseph-Burke commented on src/components/filterable-table/TablePagination.vue
> +      }
Double nesting conditionals is a bit of a bad habit I would say. This whole if-else thing is quite hard to understand at first glance. Some comments would really help.

I've had a think about some ways to refactor but it's a bit tricky...but really we should do everything possible to avoid this kind of big 'if'/'else' thing

2022-07-06 15:28 UTC, Joseph-Burke commented on src/components/filterable-table/TablePagination.vue
> +}
👍🏻

2022-07-06 16:33 UTC, Maxycle commented on CHANGELOG.md
>  - Feature:
OK so I should have mentioned that before I ask for my PR to be reviewed. Basically that new release will be 2.2.3 (not 2.2.2). 2.2.2 is the previous release that I made and I forgot to merge it (the release-2.2.2 branch with updated CHANGELOG and package.json) back into develop. Main has been updated properly but not develop. My fault...

2022-07-06 17:04 UTC, defaye commented on src/components/filterable-table/TablePagination.vue
> +        <div v-if="config.pagination.pageNumbers">
If statement on the inside of a loop should ordinarily be associated to data within an iteration of each loop. This to me looks like it should be outside the loop. Also, expressions generally should be expressed as either a computed property with a more meaningful name, or in the case that it is dependent on some argument, as a method instead.

There seems to be a lot of occurrences in this code that could benefit from using `const`s more frequently to help describe an expression before a condition and things like that.

2022-07-06 17:08 UTC, defaye commented on src/components/filterable-table/TablePagination.vue
> +      this.$store.dispatch("filterableTable/updateRequestedPage", obj);
Yes also the `obj` is not very descriptive of the argument. All variables should have some description. This could be something like `payload` or `filterableTableOptions` or something to this effect that makes it very distinct when read in the the code

2022-07-06 17:10 UTC, defaye commented on src/components/filterable-table/TablePagination.vue
> +            };
Ternary operators should never be used for complex literals/complex expressions. 

This is another case in which variable assignment is not being appreciated enough. More variables than less is a mindset to have

2022-07-06 17:14 UTC, defaye commented on src/components/filterable-table/TablePagination.vue
> +          this.totalPages
This code is very difficult to follow and maintaining it would also be difficult. You must use more variables to make sense of what is going on line by line. If you tell a short story through good variable names you won't need to add many comments.

If the code is littered with expressions that are not assigned to variables it makes things difficult to read. There should be  a warning for a high unassigned expression count. 

When you start to assign to variables you will also allow yourself to see how deep logic like this could be broken up into smaller chunks with methods instead. You can never make this kind of refactor if you've only got expressions.

2022-07-06 17:15 UTC, defaye commented on src/components/filterable-table/TablePagination.vue
> +      let lastPageOnPagination
No, avoid using this kind of assignment always, it's more difficult to maintain. 
Do assign sensible defaults to `let`s though.

2022-07-06 17:17 UTC, defaye commented on src/components/filterable-table/TablePagination.vue
> +      return pages;
Yes, `import { range } from 'lodash'` or something like that -- always check if there's a function you can use from lodash to achieve more mundane routines that have been done a thousand times

2022-07-06 17:23 UTC, defaye commented on src/components/filterable-table/TablePagination.vue
> +      if (this.totalItems == 0) {
Always use `===` instead of `==` for comparison unless you know exactly why you are dropping to type coercion

2022-07-06 17:24 UTC, Maxycle commented on src/components/filterable-table/TablePagination.vue
> +        <div v-if="config.pagination.pageNumbers">
So I remember reading somewhere that it's not advised to have v-for and v-if in the same div/element that's why I moved it to the button.

2022-07-06 17:29 UTC, defaye commented on src/components/filterable-table/TablePagination.vue
> +        this.config.pagination.numberOfPageButtonsToShow;
I don't think this works.

Maybe you mean

```
const { config: { pagination: { numberOfPageButtonsToShow } } } = this.config.pagination
```

? Or am I missing something.
At least, this may be more arduous than what was there before

2022-07-06 17:37 UTC, Maxycle commented on src/components/filterable-table/TablePagination.vue
> +        this.config.pagination.numberOfPageButtonsToShow;
I do not understand this refactoring...

2022-07-06 18:28 UTC, Maxycle commented on src/components/filterable-table/TablePagination.vue
> +      }
I have used a switch statement (containing if statement) and added some comments.

2022-07-06 22:09 UTC, defaye commented on src/components/filterable-table/TablePagination.vue
> +      }
It's not much better than before to be honest. :shrug: 

There should be rulers set in your editor that we put in together long ago. They are 80 char and 120 hard limit.

The 80 char is a cue to tell you to break a line. The 120 char limit is a cue to tell you it's unacceptable now that lines are creeping over it.

The comments should be broken manually over multi-lines, rather than relying on the editor wrap to do this. It makes it really difficult to read.

You can use

```
/**
 * This is a style for
 * multi-line comments which
 * is nice and clean.
 */
```

The indentation of the asterisks and the termination and starting asterisk pattern is important for this style of comment.

Otherwise just do

```
// Simpler
// multi-line
// comment.
```

But this is ugly TBH. In any case don't break the 80char limit if you can. Certainly not 120.
Comment above a line if it's long, at the end of a line only if it's really short comment.

Using switch like an if statement (two cases true and false) is definitely an anti-pattern.

Maybe makes sense for someone to help refactor this in pair programming shadowing Joe for another take on it or I can do this with you tomorrow

2022-07-06 23:24 UTC, Maxycle commented on src/components/filterable-table/TablePagination.vue
> +        <div v-if="config.pagination.pageNumbers">
The parent div has a class `pagination__content` which has a display property with `flex` value. If I wrap the for loop in a div (with the if statement), the flex won't be applied to the for loop and all the page numbers will stack up vertically.

2022-07-06 23:39 UTC, Maxycle commented on src/components/filterable-table/TablePagination.vue
> +        this.config.pagination.numberOfPageButtonsToShow;
Nice. But is there an advantage in doing it this way ? Or is the advantage that you could assign values to many variables at once (as in the example with foo and bar) ??

2022-07-07 00:21 UTC, Maxycle commented on src/components/filterable-table/TablePagination.vue
> +          this.totalPages
I almost wrote a book here...

2022-07-07 15:43 UTC, merged